### ISSUE TITLE
Conn (struct) with rw does not initialize - causes panic

### ISSUE THREAD

**Issue by rickcollette** [rickcollette/telnetter#1]
at runtime, there is a nil pointer panic that occurs when you use Conn rw
tested with the VariDial application found in @rickcollette github repo.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x56b431]

goroutine 8 [running]:
github.com/rickcollette/telnetter.(*Conn).Write(...)
        /home/USERNAME/go/pkg/mod/github.com/rickcollette/telnetter@v0.0.0-20230822224930-d3eb0c694643/conn.go:98
main.sendMessage(0xc00007a1e0, {0xc00001e090?, 0xc000066d38?})
        /home/USERNAME/VariDial/main.go:295 +0x51
main.showFile(0xc00007a1e0, {0x697644, 0x9})
        /home/USERNAME/VariDial/main.go:182 +0x107
main.handleConnection(0xc00007a1e0, 0x0?, 0xc000012060)
        /home/USERNAME/VariDial/main.go:232 +0xa9
created by main.main in goroutine 1
        /home/USERNAME/VariDial/main.go:290 +0x1c6

**Comment by rickcollette** [comment]
the culprit seems to be here - i need to initialize rw explicitly where  telCon := &Conn{conn: conn, } is setup.

```
func (l *Listener) Accept() (*Conn, error) {
    conn, err := l.listener.Accept()
    if err != nil {
        return nil, err
    }

    telCon := &Conn{
        conn: conn,
    }

    go handleConnection(conn, l.timeout, telCon)

    return telCon, nil
}
```


so :

```
 telCon := &Conn{
        conn: conn,
    }
```

becomes:

```
	telCon := &Conn{
		conn: conn,
		rw: conn,
	}
```

**Comment by rickcollette** [comment]
this fixed it. initializing the rw upon Accept was the fix.
